language: node_js
env: CI=true
node_js:
- stable
services:
- mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
before_script:
- mongod --version
- export NODE_ENV=CI
- "./bin/upgrade-model"
- npm install -g gulp
- npm install -g sally-js
- mkdir logs
script:
- gulp
- sally verify logs/*.sal
- pkg=$(npm pack)
- npm install -g --quiet $pkg
before_install:
- mkdir ~/.stormpath
- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
  -in config/CI/stormpath.properties.travis.enc -out ~/.stormpath/apikey.properties -d
- chmod go-rwx ~/.stormpath/apikey.properties
