language: node_js
env: CI=true
node_js:
- stable
services:
- mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
before_script:
- mongod --version
- export NODE_ENV=CI
- "./bin/upgrade-model"
- npm install -g gulp
- npm install -g sally-js
script:
- gulp
- sally verify logs/*.sal
- pkg=$(npm pack)
- npm install -g --quiet $pkg
