language: node_js
env: CI=true
node_js:
  - stable
services:
  - mongodb
before_script:
  - npm install -g gulp
  - npm install -g sally-js
  - mkdir logs
script:
  - mongo ecom --eval "db.dropDatabase()"
  - gulp
  - sally verify logs/*.sal
  - pkg=$(npm pack)
  - npm install -g $pkg
