# gitversion will change the version number
version: x-{build}

clone_folder: c:\projects\yappy

services:
  - mongodb

# Test against this version of Node.js
environment:
  nodejs_version: "5.2"
  NODE_ENV: CI
  CurrencyLayerKey:
    secure: sv2yXw6Fip8E0hWm9biXFvIWNcTik0erH+WQ60L6zfrdE/MrJm4gikZCpMcaadIY
  SallySecret:
    secure: 8GMDWpnDMeLsTQAwH2rocg==
  StormPathSecret:
    secure: B/Rx2i5D/VwgGh3A0kyfSNolRcnD+NU3n0SOIBVCbRQ=

# Install scripts. (runs after repo cloning)
install:
  - choco install gitversion.portable -pre -y
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - ps: gitversion /output buildserver >gitversion.log

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # give mongodb time to startup
  - ping 127.0.0.1 -n 5 > nul
  # upgrade the database
  - node bin\upgrade-model
  # run tests
  - npm test

# Don't actually build.
build: off

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: false

