# gitversion will change the version number
version: x-{build}

# Install scripts. (runs after repo cloning)
install:
  - choco install gitversion.portable -pre -y
  - npm install
  - ps: gitversion /output buildserver >gitversion.log

# Post-install test scripts.
test_script:
  - npm test

# Don't actually build.
build: off

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: false

